### ISSUE TITLE
Allow Merged Group Variables

### ISSUE THREAD

**Issue by p-rintz** [ipr-cnrs/nftables#11]
Hi there,

I have the following use case that I would like to fulfil with this Ansible role.
Imagine the following setup:
Server A has two (or more) Ansible groups.
Group "webserver" and Group "email_server".

Webserver has the following rules (just nft_input_group_rules as example):
```
nft_input_group_rules:
  297 local:
    - iif mgmt accept
  298 storage:
    - iif storage accept
  299 cluster:
    - iif cluster accept
```
Email_server has the following:
```
nft_input_group_rules:
  310 allowemail:
    - ip saddr @allowemail ct state new accept
```

If I set the variables inside the group_vars as you mentioned in the readme, the group vars of group "email_server" would be overwritten by those of group "webserver" and only the firewall rules for the webservers would be applied to server A.

Instead I would like both variables of the groups to be applied, so that the server gets the firewall rules for both the "webserver" and "email_server" group.

```
        # 297 local
        iif mgmt accept
        # 298 storage
        iif storage accept
        # 299 cluster
        iif cluster accept
        # 310 allowemail
        ip saddr @allowemail ct state new accept
```

Is this something you would be interested in as a pull request?
I have written the necessary changes already on my end, though I would need to make it more modularized and test it more to actually open up a pull request.

Currently the default behaviour would stay the same as it is now.
There would be two new variables that are optional to be set if one would like to use this.

"merged_groups": true/false (false being the default)
"merged_groups_dir": directory with the nftables variables inside text files named after the ansible groups. (ie. "webserver" or "email_server")

Thanks.

**Comment by gardouille** [comment]
Hi :)

Yeah, I definitively see the limitations of the current variable system…

A "merge option" can be a good idea and also make my configuration easier :)

/me eager to see your implementation.
