### ISSUE TITLE
update_cache: true breaks nftables installation on Gentoo

### ISSUE THREAD

**Issue by VTimofeenko** [ipr-cnrs/nftables#24]
I am writing molecule tests to test the role on Gentoo and found that the role throws an error when installing the package:
```
fatal: [Gentoo]: FAILED! => {"attempts": 3, "changed": false, 
"msg": 
"Unsupported parameters for (ansible.legacy.portage) module: update_cache. 
Supported parameters include: sync, deep, keepgoing, depclean, update, newuse, oneshot, usepkg, onlydeps, jobs, quietfail, package (name), loadavg, noreplace, getbinpkgonly, state, verbose, nodeps, usepkgonly, changed_use, quietbuild, quiet, getbinpkg."}
```

Looks like 8fad9d75 added 
```
update_cache: true
```
to installation task. 

According to the [doc](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html#ansible-collections-ansible-builtin-package-module), the values supported by the ansible.builtin.package are:
* name 
* state
* use

Was this change made in the context of the molecule tests? If so, would it be possible to move the package cache into preparation playbooks making them distro-specific?

**Comment by VTimofeenko** [comment]
Removed the line, all tests seem to pass, see 542f562

**Comment by gardouille** [comment]
Looks good for me, you did all the job :)

Also asking to @kravietz as he added `update_cache`

**Comment by gardouille** [comment]
I created a dedicated task to update repositories and keep it as simple as possible (only update_cache) and exclude Gentoo family. The update_cache seems available on the other tested os (arch, debian&co, fedora&co).

Please let me know if everything works fine on your side and i will publish a new minor release :)

**Comment by VTimofeenko** [comment]
Thanks! Just tested, molecule test passes on c7512f7

**Comment by kravietz** [comment]
I just returned from holiday but I see all questions are resolved and everything is working fine :)
