### ISSUE TITLE
Reload invalid ruleset leads to no firewall rules

### ISSUE THREAD

**Issue by meersau** [ipr-cnrs/nftables#3]
If an invalid syntax is added to the rulebase, a changed rulebase stops/starts the service. So
stop flushes the rulebase and start fails. A reload will not load the rulebase if there any errors.

A handler with state `reloaded`, which runs when changes to the rules are made, instead of state `restarted` would not result in a host without firewall rules.

**Comment by gardouille** [comment]
Thank you ;)
The first run now (re)start the nftables service.
At next runs, the service will just be `reloaded` to apply new rules if valid.
