### ISSUE TITLE
Enabling the nftables service on notification prevents idempotency

### ISSUE THREAD

**Issue by mjourdan** [ipr-cnrs/nftables#34]
Relying on a handler to enable the service is a problem for idempotency. If the role got interrupted (for example because it got stuck), no change will trigger the handler on consecutive run. As a result, nftables will stay deactivated and stopped.

**Comment by stejoo** [comment]
#36 has been merged. I think this can be closed?

**Comment by kravietz** [comment]
@stejoo Yes, it's merged so closing!
