### ISSUE TITLE
Ubuntu 16.04 not compatible

### ISSUE THREAD

**Issue by rrooij** [ipr-cnrs/nftables#4]
Ubuntu 16.04 is not compatible since it uses and old version of nftables which doesn't support the default's config syntax. Running the role will result in:

```
{"changed": false, "msg": "Unable to start service nftables: Job for nftables.service failed because the control process exited with error code. See \"systemctl status nftables.service\" and \"journalctl -xe\" for details.\n"}
```

In the journal logs:

```
/etc/nftables.d/filter-output.nft:19:20-20: Error: syntax error
```

Ubuntu 18.04 hosts work fine.

**Comment by gardouille** [comment]
Hmm… I don't have any Ubuntu for testing. If you know the rules that are a problem, we can try a specific vars files for Ubuntu 16.04.

**Comment by ektich** [comment]
Hi @gardouille: I've got the following errors when trying to load tables generated by default:
```
In file included from /etc/nftables.conf:17:9-52:
/etc/nftables.d/filter-output.nft:5:20-20: Error: syntax error, unexpected '$', expecting '{'
e filter hook output priority 0; policy drop;
                   ^
In file included from /etc/nftables.conf:17:9-52:
/etc/nftables.d/filter-output.nft:10:20-20: Error: syntax error, unexpected '$', expecting '{'
host
                   ^
In file included from /etc/nftables.conf:17:9-52:
/etc/nftables.d/filter-output.nft:19:20-20: Error: syntax error, unexpected '$', expecting '{'
port @out_udp_accept ct state new accept
                   ^
In file included from /etc/nftables.conf:17:9-52:
/etc/nftables.d/filter-output.nft:24:20-20: Error: syntax error, unexpected '$', expecting '{'
cept ct state new accept
                   ^
In file included from /etc/nftables.conf:17:9-52:
/etc/nftables.d/filter-output.nft:29:20-20: Error: syntax error, unexpected '$', expecting '{'
unter accept
```

 - Ubuntu: "16.04.6 LTS (Xenial Xerus)"
 - nftables: 0.5+snapshot20151106-1

**Comment by gardouille** [comment]
Never worked with a version previous to 0.7 (Debian Stretch)…

The "only" solution i see is to adapt the configuration to work with <0.7 such as : 
* Using your own templates. You can specify another template to almost all files (eg. rewriting **nft_main_conf_content** var).
* Be sure to use only compatible syntax. I am not sure you can use **include** for example… I can't find any release announcement before [0.7](https://www.spinics.net/lists/netfilter-devel/msg45557.html).
* Rewrite defaults rules (nft_global_default_rules, nft_input_default_rules, nft_output_default_rules, nft__nat_default_prerouting_rules and nft__nat_default_postrouting_rules).

**Comment by kravietz** [comment]
@ektich This is the core problem:
```
nftables: 0.5
```
Older Ubuntu distros were lagging behind the `nftables` releases and plagued by various bugs present in very old versions of `nft`. This can be to some extent mitigated by using a newer build from Snap Store https://snapcraft.io/nftables-pk if Xenial supports snaps, otherwise I would just recommend rebuilding the package from source with new upstream code. Also note that Xenial is EOL since April 2021.
