### ISSUE TITLE
On Archlinux, iptables can't be removed

### ISSUE THREAD

**Issue by rdbisme** [ipr-cnrs/nftables#43]
```
error: failed to prepare transaction (could not satisfy dependencies)
:: removing iptables breaks dependency 'iptables' required by fail2ban
:: removing iptables breaks dependency 'iptables' required by iproute2
:: removing iptables breaks dependency 'iptables' required by systemd
```

Maybe installing `iptables-nft` instead would solve the problem?

**Comment by kravietz** [comment]
This can be worked around by this flag, as it disables attempts to remove  `iptables` completely:
```
nft_old_pkg_manage: false
```
The `iptables-nft` package duplicates `iptables` so it's also a solution. Not sure if that doesn't bring any compatibility issues?
