### ISSUE TITLE
Issue new tag

### ISSUE THREAD

**Issue by stejoo** [ipr-cnrs/nftables#49]
@kravietz you have been hard at work merging stuff. Thank you :heart: !

Would it be possible to tag/release a new version of the role to mark this occassion? :+1:

**Comment by gardouille** [comment]
Thank you to @kravietz for all his work and to you @stejoo for your contributions !

A new release, v2.1.0 is available on Galaxy :+1:

**Comment by gardouille** [comment]
Again, thanks to @kravietz , new release are now automatically upload to Ansible Galaxy (PR #45 ) and v2.2.1 just arrived :)
