### ISSUE TITLE
Galaxy

### ISSUE THREAD

**Issue by kravietz** [ipr-cnrs/nftables#67]
@ipr-cnrs would it be possible to refresh the Ansible Galaxy token to enable automatic loading of new releases? It seems like it's not working now due to some misconfiguration on the Galaxy side or mismatch between here and Galaxy:

```
===== PROCESSING LOADER RESULTS ====
overriding namespace name via metadata: ipr_cnrs
legacy namespace ipr_cnrs does not exist
```

https://github.com/ipr-cnrs/nftables/actions/runs/10623414734/job/29449793723

**Comment by gardouille** [comment]
Looking…

Sorry, role related to my previous work, i will have to move it to a new namespace… one day

**Comment by gardouille** [comment]
Fixed with https://github.com/ipr-cnrs/nftables/commit/1050fe8df5adc745862ab422eb5ba52b8cca28f2

Obviously Galaxy made some changes with the namespace… 🤷 New namespace is now ipr**-**cnrs :  
https://galaxy.ansible.com/ui/standalone/roles/ipr-cnrs/nftables/

Thank you for all your work @kravietz !
